DROP TABLE PERSON;
DROP SEQUENCE EXAMPLE_SQ RESTRICT;


CREATE TABLE PERSON (
  ID DECIMAL NOT NULL,
  NAME VARCHAR(128),
  PRENAME VARCHAR(128),
  PRIMARY KEY (ID)
);


INSERT INTO PERSON(ID, NAME, PRENAME) VALUES (1,'Mueller','Bernd');
INSERT INTO PERSON(ID, NAME, PRENAME) VALUES (2,'Berger','Stefan');

CREATE SEQUENCE EXAMPLE_SQ START WITH 3 INCREMENT BY 1;

